### ISSUE TITLE
Enviroment setup bad link

### ISSUE THREAD

**Issue by kmather73** [udacity/robotics-nanodegree-issues#1]
The link in Lesson 3 of the Project 1 for the environment setup does not link to the right repo just goes to the github's main page, should link to https://github.com/udacity/RoboND-Python-StarterKit

**Comment by kmather73** [comment]
The link just goes to the main github page and not https://github.com/udacity/RoboND-Python-StarterKit

**Comment by kmather73** [comment]
Made a mistake,  didn't see the link at the bottom of the page, sorry

**Comment by ryan-keenan** [comment]
no worries, this was worded strangely, which I think might have led to confusion so I've reworded it!
