### ISSUE TITLE
Controls 1-13 PD Controller - Graph Legend Wrong

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-nanodegree-issues#100]
In the controls section, lesson 1-13 "Building a PD controller" there is an image of the graph showing the expected output. However the legend shows 'u_p' and 'u_i' (suggesting proportional and integral), however since the lesson is about PD it should be updated to 'u_d'

**Comment by adammalpass** [comment]
Also in the pd_controller.py code file it says "# Good luck designing your proportional integral controller!" --> This should also be updated to 'Proportional Differential'.

**Comment by kylesf** [comment]
On it!

**Comment by kylesf** [comment]
Fixed!
