### ISSUE TITLE
Controls lesson 1.5

### ISSUE THREAD

**Issue by dandrews7396** [udacity/robotics-nanodegree-issues#102]
quiz asks for the minimum control effort for the quadrotor to lift, to 5s.f. It accepts the answer 1.5107, which is taken from the result of g*m/c (1.51074). However, as is it even stated within the code, the quadrotor will not take off until the control force is greater than g*m/c. This means that the required answer of 1.5107 is incorrect and, as the actual required force is 1.51075, should be 1.5108.

**Comment by kylesf** [comment]
Fixed, thanks!

**Comment by gurparteek** [comment]
1.510741 is also greater than 1.51074, so is 1.5107400000001, the greater number need not necessarily be 1.51075. The original answer of 1.5107 was correct.

**Comment by kylesf** [comment]
Okay fair point, I will change back

**Comment by dandrews7396** [comment]
No it's not. I'm currently mobile, but if I remember correctly, the code
contains the conditional statement that it must be greater than, not equal
to. If it is equal to, then that condition will not be met and it will
fail. Maybe my example was flawed, but my statement still stands

On 29 Aug 2017 8:02 pm, "Kyle Stewart-Frantz" <notifications@github.com>
wrote:

Okay fair point, I will change back

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/udacity/robotics-nanodegree-issues/issues/102#issuecomment-325762781>,
or mute the thread

**Comment by kylesf** [comment]
Made it 3 significant figures with 1.52 as answer.
