### ISSUE TITLE
Mistake on solution of Lesson1-21 of Controls

### ISSUE THREAD

**Issue by estringana** [udacity/robotics-nanodegree-issues#103]
Looking at the solution proposed, the following mistake was spotted
```
soln = hover(p)
cost = cost_fun(soln)
best_cost = cost

if cost < best_cost:
```
That condition will be never evaluated to true. However, the solution still works

**Comment by thomas-at-em** [comment]
You are absolutely right. Thanks very much for reporting! Should be fixed now.
