### ISSUE TITLE
Intro to controls, lesson 18

### ISSUE THREAD

**Issue by sychaichangkun** [udacity/robotics-nanodegree-issues#106]
the solution to the exercise calculate d via `d = self.kd_ * (self.alpha * delta_error / delta_time + (1 - self.alpha))`.   It seems incorrect. In lesson 18, it's told D[k] = alpha * delta_error/delta_t + (1-alpha)*D[k-1]. I think it should be `d = self.kd * self.alpha * delta_error / delta_time + (1 - self.alpha) * d_last`

**Comment by sychaichangkun** [comment]
Sorry, I mean lesson 22, the solution seems incorrect

**Comment by thomas-at-em** [comment]
Yes, you are correct! Thanks for reporting that.
