### ISSUE TITLE
Controls Lesson 2-12 Broken Link

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-nanodegree-issues#108]
The link back to dynamic config section is broken. It refers to the beta version of the nanodegree and so can't be accessed.

**Comment by adammalpass** [comment]
Link in 2-13 to cascade control section has same problem, referring to beta ND

**Comment by adammalpass** [comment]
And link in 2-13 to dynamic reconfig

**Comment by kylesf** [comment]
Fixed, thanks!
