### ISSUE TITLE
control lesson 1: tuning strategies 2

### ISSUE THREAD

**Issue by lisajlau** [udacity/robotics-nanodegree-issues#110]
in the solution.py, the cost is set to best_cost on line 139. I think this is an error, and should be removed. It is followed by an if statement that compares cost and best_cost, which would always return false
line 139: best_cost = cost
line 141: if cost < best_cost:

**Comment by lisajlau** [comment]
according to the image, it is set after the comparison has been done.

**Comment by thomas-at-em** [comment]
This was reported by another student. I believe it should be fixed now.
