### ISSUE TITLE
Make Reflection Quizzes Editable

### ISSUE THREAD

**Issue by Kni8tF0x** [udacity/robotics-nanodegree-issues#111]
In the Controls Lessons, there are several quizzes where we are provided with the opportunity to vary some code parameters and reflect on the effects they have on the result. It would be nice if we could edit our entries once they have been submitted, in order to correct typos or add more information.

**Comment by kylesf** [comment]
I will check this out, thanks for the feedback!

**Comment by adammalpass** [comment]
Ah yes I noticed that too! I just added my first iteration, saved, and then couldn't change again... would be great to update this!

**Comment by kylesf** [comment]
Working on looking into guys!

**Comment by kylesf** [comment]
Official ticket has been made!
