### ISSUE TITLE
Controls 2-13 Attitude Controller launch

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-nanodegree-issues#114]
As just discussed with Kyle and Brandon on Slack the hover node _must not_ be running whilst attitude controller is. Already Kyle removed the note that alluded to this, but would be better to explicitly state that they should not be run at same time.

Also I found that there seems to be some trash left in the comms somewhere and you have to restart the terminal / restart the sim in between closing hover controller and attitude controller, else it wont work. Might be good to add another commented suggesting people restart if they are having issues.

**Comment by kylesf** [comment]
Added some verbiage!
