### ISSUE TITLE
Controls - Sim Comms Issues

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-nanodegree-issues#116]
As discussed extensively on Slack we had many issues connected the sim to VM, especially with VMWare Fusion on Mac. Please add some notes to lesson to explain this and potential fixes for future students.

Also I noted that my ROS_IP seems to change sometimes after restarting the terminal in the VM, so must be careful to update the ros_settings file each time. Would be good to add a note mentioning this.

**Comment by kylesf** [comment]
Made the changes!
