### ISSUE TITLE
Controls - zn_tuner and twiddle_tuner not giving useful results

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-nanodegree-issues#117]
The automatic PID tuning scripts for hover controller do not give any useful results. They don't even produce enough thrust for the drone to lift-off the ground.

**Comment by adammalpass** [comment]
Probably issue #121 is the root cause of this. I'll re-test can keep you posted.

**Comment by adammalpass** [comment]
Twiddle is now working after #121 fix!

**Comment by kylesf** [comment]
Great!
