### ISSUE TITLE
crl TensorFlow L01E09

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-nanodegree-issues#118]
Quiz: my answer matches the solution but when I run I am getting a "uninitialized value variable" error.

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/4405411f-bdc8-43fb-9e2b-b4b98a61c760/modules/375d6b1e-b31a-4d2e-b33a-996167faf77e/lessons/a4a80417-00cb-4a9c-8cc4-3a091414baa2/concepts/1c06a07a-17d7-438e-b31f-2d86864410fc

**Comment by kylesf** [comment]
@sahiljuneja Any input with this?

**Comment by kylesf** [comment]
@zenetio In the future please your designated waffle board.

**Comment by sahiljuneja** [comment]
Which quiz in particular? ANd can you share the entire error you get?

**Comment by zenetio** [comment]
I found the issue. I forgot to use the initialization process.

**Comment by sahiljuneja** [comment]
Oh cool. I will close this then.
