### ISSUE TITLE
small comment fix

### ISSUE THREAD

**Issue by Chambana** [udacity/robotics-nanodegree-issues#12]
The comment below "#Perform rotation, translation and clipping all at once"  in the transformation exercise sample code doesn't make sense in this context.  You've already done the rotation and translation in the 2 preceding lines.  The subsequent line only does the clipping.  Perhaps this comment should be at the top of the function itself?

def pix_to_world(xpix, ypix, xpos, ypos, yaw, world_size, scale):
    # Apply rotation
    xpix_rot, ypix_rot = rotate_pix(xpix, ypix, yaw)
    # Apply translation
    xpix_tran, ypix_tran = translate_pix(xpix_rot, ypix_rot, xpos, ypos, scale)
    # Perform rotation, translation and clipping all at once
    x_pix_world = np.clip(np.int_(xpix_tran), 0, world_size - 1)
    y_pix_world = np.clip(np.int_(ypix_tran), 0, world_size - 1)
    # Return the result
    return x_pix_world, y_pix_world

**Comment by ryan-keenan** [comment]
thanks for catching this!  was a leftover code comment from a previous incarnation of this quiz. fixed now
