### ISSUE TITLE
Controls lab twiddle.py - not checking for <0 values of self.params[i]

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-nanodegree-issues#120]
*I added pull request on Github to fix this issue - please check and accept! Thanks :) *

In the controls lab in the twiddle.py file the self.params[i] values should not be allowed to go below 0, but code doesn't check for this.
Sometimes when running the algorithm the values can be seen to go below 0.
I added a check if self.params_[i] < 0 then limit value to 0.

**Comment by kylesf** [comment]
Done, Thanks!
