### ISSUE TITLE
Controls 2.12 - rqt reconfigure fails

### ISSUE THREAD

**Issue by thatting** [udacity/robotics-nanodegree-issues#122]
Controls, lesson 2-12, "dynamic_reconfigure" - I cannot launch rqt_reconfigure with command: "$ rosrun rqt_reconfigure rqt_reconfigure"

These steps work fine:
a) Launch of roscore
b) Launch of drone simulator
c) Checking of topic /quad_rotor/pose for messages
d) Launch of hover controller node

However, when I try to launch the rqt_reconfigure instance, I get following error:

$ rosrun rqt_reconfigure rqt_reconfigure
[rospack] Error: package 'rqt_reconfigure' not found

Somehow the package is missing on my VM ?
(I'm using the lastest VM version: V2.1.0)

**Comment by thatting** [comment]
(continued...) The rqt_reconfigure package is present on my 'old' VM (5.22.17) but, somehow, it is not present on my new VM (2.1.0):

**VM (v5.22.17):**
robond@udacity:~$ rospack find rqt_reconfigure
/opt/ros/kinetic/share/rqt_reconfigure

**VM (v2.1.0) :**
Do you want to source ROS in this workspace (y/n): y
ROS sourced!
robond@udacity:~$ rospack find rqt_reconfigure
[rospack] Error: package 'rqt_reconfigure' not found

 



I have a re-run Software Updater inside my new VM (2.1.0), and it says "The software .....is up-to-date", so there are no updates left to download.

**Comment by thatting** [comment]
The problem has now been solved!   I ran the apt-get command below in the terminal instead of using menu option System Tools/ Software Updater in the VM:

sudo apt-get install ros-kinetic-rqt-reconfigure
 
So, rqt_reconfigure works now in my VM.

**Comment by kylesf** [comment]
Cool, It seems this is installed in the current VM. Not sure what may have happened.
