### ISSUE TITLE
Quad sim crashes after zn tuner runs

### ISSUE THREAD

**Issue by oldtopos** [udacity/robotics-nanodegree-issues#126]

**Comment by oldtopos** [comment]
OS X Sim - Sim crashes or shuts down after three zn_tuner runs.  Setting all dynamic parms to zero causes the failure.

**Comment by kylesf** [comment]
Will look into it. Thanks!

**Comment by bkinman** [comment]
Seems like there is a bug in DroneSim, adding Noam.
