### ISSUE TITLE
repeated word in Skills Recap lesson

### ISSUE THREAD

**Issue by Youssef-Khaky** [udacity/robotics-nanodegree-issues#129]
"..you combined your perception and and decision making robotics skills ..."
This can be found on the last udacity explores.

**Comment by sahiljuneja** [comment]
Could you please the specific name of the lesson and which section it was in?

For example " Udacity Explores - Robot Grasping, Cover Letter Review - Cover Letter Components" would be one good way to let us know of the section directly. Otherwise, it can be difficult to pinpoint it. Thanks! :)

**Comment by Youssef-Khaky** [comment]
Udacity Explores - SwarmRobotics --> Networking in Robotics --> skill recap

**Comment by sahiljuneja** [comment]
Thanks! Fixed.
