### ISSUE TITLE
issue with sample code in "Where to Go?"

### ISSUE THREAD

**Issue by Chambana** [udacity/robotics-nanodegree-issues#13]
2 issues with the sample code in this section:

First, the variable "image" is never defined and the code won't run as-is. 
 These 2 lines need to be added to the top of the code:
import matplotlib.image as mpimg
image = mpimg.imread('angle_example.jpg')

Second, the variable "threshed" is never defined as well.  I believe it should be replaced with colorsel.  Or, colorsel should, more likely, be renamed threshed.

**Comment by ryan-keenan** [comment]
Great catch!  I've made the suggested changes
