### ISSUE TITLE
Hyperlink not working

### ISSUE THREAD

**Issue by Youssef-Khaky** [udacity/robotics-nanodegree-issues#130]
In "Resume Review Project (Entry-level)" the hyperlink for "Professional Profile" is not working for me.

**Comment by kylesf** [comment]
Can you provide me more details on the location of this error? This is managed by careers team.

**Comment by Youssef-Khaky** [comment]
It can be found here:
Extracurricular -->4.Udacity Explores - Robot grasping --> Project: Resume Review project (Entry-level) --> Resume Review Project (Entry-level) --> "Udacity students and alumni via your >>>Professional Profile.<<< "

**Comment by kylesf** [comment]
Ticket has been submitted.

**Comment by kylesf** [comment]
Should be fixed now!
