### ISSUE TITLE
XOR quiz update lesson 1.8 in deep learning

### ISSUE THREAD

**Issue by Youssef-Khaky** [udacity/robotics-nanodegree-issues#132]
In lesson 1: intro to neural networks, the quiz for XOR says "However, the perceptrons A , B, C, and D don't indicate their operation. In the following quiz, set the correct operations for the four perceptrons to calculate XOR."
The last AND is already filled up, there is no D.

**Comment by sahiljuneja** [comment]
Fixed, thanks!
