### ISSUE TITLE
Deep Learning: Quiz in Lesson 1.25 issue

### ISSUE THREAD

**Issue by chedanix** [udacity/robotics-nanodegree-issues#136]
This has been mentioned in Slack.

Issue: The solution adds gradient to the weights and the bias, instead of subtracting as shown in lecture. But yet the resulting plot is accurate.

My proposed solution: To make the quiz more similar to the lecture material. I think you need to 1) change 0 to 1 and 1 to 0 in data.csv and 2) negate DErrorsDx1 and DErrorsDx1 in the current solution.

**Comment by sahiljuneja** [comment]
Thanks for pointing this out. Having this looked into.
