### ISSUE TITLE
Possible error in probability value in cross entropy lesson

### ISSUE THREAD

**Issue by dwazalwar** [udacity/robotics-nanodegree-issues#139]
In intro to Neural networks Cross Entropy 1 towards end of lesson (check at 2.22), in right model instead of -log(0.2), it should be -log(0.7).

**Comment by dwazalwar** [comment]
![Cross-Entropy-Possible Error.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59bdb07c30578b0012e5757c/125516c66e82c728ace21e0d46cb86953091ce8c81fdad4cb444bda42655347a2b08a66b5597f127ad0037431f1d11f6140b1b56f6eb8c22a4b5382482550ab9d56d5c70c63d18aeb8d01cea08b832975dc7e7e2de139db17770a599855d3f170f198cff5833a09d4dc158ff4ee65f18.png)

**Comment by sahiljuneja** [comment]
A correction note was provided a while ago. Thanks for reporting!
