### ISSUE TITLE
Missing Plot Show in colorthreshold.py

### ISSUE THREAD

**Issue by ghost** [udacity/robotics-nanodegree-issues#14]
Go to Introduction To Robotics > Search and Sample Return > The Perception Step 
the color_threshold.py is missing line 'plt.show()' at the end to display the plot 

System : 
Windows 7
Python 3.6.1

**Comment by ryan-keenan** [comment]
Thanks for reporting this!  In fact, within our quiz editor we need to take slightly different steps to actually render the plot so the `plt.show()` is left out by design.  As you have seen, however, this is required if you're running the code on your local machine.

**Comment by ryan-keenan** [comment]
I've added a comment at the bottom of each code quiz that you should add `plt.show()` if running the quiz code on your local machine
