### ISSUE TITLE
Robotic Arm: Pick and Place - couple of dead 'here' links

### ISSUE THREAD

**Issue by jeremyolsen** [udacity/robotics-nanodegree-issues#140]
Slide 20 of the Submission slide has a couple of dead "here" links.  These are the ones I found:

1. Instructions on how to do the math behind IK can be found here

2. Instructions on proper formatting for your IK code and details of how IK_server.py works can be found here

URL of page with the issue:
https://classroom.udacity.com/nanodegrees/nd209/parts/7b2fd2d7-e181-401e-977a-6158c77bf816/modules/8855de3f-2897-46c3-a805-628b5ecf045b/lessons/91d017b1-4493-4522-ad52-04a74a01094c/project

**Comment by sahiljuneja** [comment]
Fixed. Thanks, Jeremy!
