### ISSUE TITLE
crl Semantic Segmentation L06E09

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-nanodegree-issues#147]

**Comment by zenetio** [comment]
The text in lesson says, in notebook, the separable_conv2d_batchnorm function adds batch normalization but the same is the case of conv2d_batchnorm(). So, I think the text should do mention of both functions.

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/4405411f-bdc8-43fb-9e2b-b4b98a61c760/modules/375d6b1e-b31a-4d2e-b33a-996167faf77e/lessons/99db3ae7-9e87-40ba-b83c-5d1428643d2d/concepts/387b8924-72cd-4661-a2e5-3aa11d4bbe3c

**Comment by sahiljuneja** [comment]
Thank you, but please use the beta-testers waffleboard. I have closed this issue here. Feel free to open one in the dedicated waffleboard :)
