### ISSUE TITLE
CNN Lab - Two of the TODO exercises are already implemented inside the Notebook

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-nanodegree-issues#149]
For the Deep Learning section, CNN Jupyter notebook lab there are a series of TODOs to be completed. For the 'train_neural_network' section and 'print_stats' section the TODO has already been implemented. Presumably left over from testing. I'm not complaining as it saved me time ;) but I'm guessing this was not the intention and so they should be deleted. It was also a little confusing as I had to try and work out if there was something _extra_ I was meant to be adding to them, but finally I released they just showed the answer already..

**Comment by sahiljuneja** [comment]
Updated to remove those solutions ;) Thanks!
