### ISSUE TITLE
Deep Learning Lesson 6-10 Equation Wrong

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-nanodegree-issues#153]
The equation for P34 is stated as P3 + H1 * (P4 - P3) / H2.

However since P3 and P4 are located along the W2 axis I'm sure it should be calculated in a similar fashion to the P12 formula above, i.e:

P34 = P3 + W1*(P4-P3) / W2

Please confirm and update? Thanks!

**Comment by sahiljuneja** [comment]
Thanks for reporting this. Fixed!
