### ISSUE TITLE
some errors occur after updating segmentation_lab

### ISSUE THREAD

**Issue by sychaichangkun** [udacity/robotics-nanodegree-issues#154]
I updated to the latest segmentation_lab(commit  eeea32f161) , but got several errors in saving model weights(missing argument), prediction(index out of bounds) and evaluation(index error).

**Comment by sychaichangkun** [comment]
so does the RoboND-DeepLearning project

**Comment by sahiljuneja** [comment]
Hey! Was this resolved for you based on the recent updates?

**Comment by sychaichangkun** [comment]
yes, resolved. Thank you.
