### ISSUE TITLE
Deep Learning Project - Missing Dependencies

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-nanodegree-issues#156]
I'm using the RoboND environment (very first version) and tried to run the Deep Learning Project. The lesson notes said we must update tensorflow and install socket-io, but I found some other missing dependencies too:

- transforms3d
- pyqt
- pyqtgraph

After I installed them it worked fine, but should be good to add this to lesson notes!

**Comment by kylesf** [comment]
Done, thanks!
