### ISSUE TITLE
'Finish and Graduate' options appears after completing first project

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-nanodegree-issues#16]
I passed the first project and since it's the only coursework currently available my Udacity home page is telling me I can finish and graduate! Might want to fix this

**Comment by ryan-keenan** [comment]
Thanks for reporting this!  I think it's fixed now.

**Comment by adammalpass** [comment]
Yes I can confirm it's fixed, thanks!

**Comment by cdlei** [comment]
👌 great to hear. Thanks @adammalpass
