### ISSUE TITLE
KR210 Forward Kinematics 2 video displays inconsistent orientation for frames 4,5, 6 and gripper.

### ISSUE THREAD

**Issue by jazzdman** [udacity/robotics-nanodegree-issues#165]
https://www.youtube.com/watch?time_continue=16&v=CNQ9CE_itBg

Start the video at about the 2:45 mark.  Just after the 2:50 mark, the vectors that define the orientation of frames 4, 5, 6 and gripper change.  Both of them can't be correct.

**Comment by haoyang-udacity** [comment]
The first one is as defined in the URDF file.
