### ISSUE TITLE
Follow Me Simulator Python script crash Win10

### ISSUE THREAD

**Issue by Thom087** [udacity/robotics-nanodegree-issues#169]
I launch the simulator in the follow me mode. As soon as I try to launch the python script It takes like 10s than it crashes. I am using Win10

**Comment by Thom087** [comment]
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fb1cbe678ec80014f362e2/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fa7923d1e770e6137f555f5c4aac41515d44aefadc22a4a42062c80d55b98e30063e937f03a6aa8316b500bf20824987bfbe834fc6eb3d37aa.JPG)

**Comment by Thom087** [comment]
The simulator somehow is still working no problem, just the python script won't work

**Comment by kylesf** [comment]
Please run `conda update --all` and see if that fixes the problem!

**Comment by kylesf** [comment]
Any updates @Thom087 ?

**Comment by adammalpass** [comment]
@kylesf @Thom087
I just spoke to student on Live Chat who had this exact same issue. I suggested to run `conda update --all` and it fixed their problem! :)

**Comment by perfalcon** [comment]
@kylesf  .. i am facing the same issue, it worked after i did "conda update --all"

**Comment by adammalpass** [comment]
Another student on Live Chat had this same issue and again the same fix solved it. So I think this one should be solved!

**Comment by danzelmo** [comment]
The update fixes the issue, but I am not sure why yet. Its on my todo list to track down the exact cause of this, I will leave this open until that fix is found.
