### ISSUE TITLE
Bug in the UI for the quizzes

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-nanodegree-issues#17]
Whenever you submit a quiz, you get a pop-up window stating whether we cleared it or not.

If you press the `Try Again` or `Continue` button in that pop-up, there's no issue.

But if you try to close the pop-up by clicking the `x` (cross) in the top-right corner of the pop-up window, it scrolls the window all the way to the top.

**Comment by ryan-keenan** [comment]
filed a ticket for this, thanks for reporting!

**Comment by kylesf** [comment]
@ryan-keenan Any updates on the JIRA ticket?

**Comment by kylesf** [comment]
@sahiljuneja Did this ever get fixed to your knowledge?

**Comment by sahiljuneja** [comment]
Nope. Just checked. The JIRA ticket is unresolved (in review) and they will get to it I'm sure. So I will close this since it's in the system and is not of high priority.
