### ISSUE TITLE
Multi-class entropy video labels don't match narration

### ISSUE THREAD

**Issue by croomjm** [udacity/robotics-nanodegree-issues#172]
at ~2:40: "y_1j is the probability of the duck being behind door j," but the image labels the door as door i. Similarly for the walrus door, which is labeled door k.

**Comment by sahiljuneja** [comment]
Hey, this is a known issue that is being looked into, although it could be a while. I will try to provide text around it till the video gets fixed, soon. You can refer to issue https://github.com/udacity/robotics-nanodegree-issues/issues/134 as well. I will close this one for now to avoid duplicates.
