### ISSUE TITLE
Deep Learning: Selecting Region when submit a Limit Increase Request in AWS

### ISSUE THREAD

**Issue by ggnohc** [udacity/robotics-nanodegree-issues#177]
In Lesson 4.33 Part 1: AWS GPU instances, in 3.  Submit a Limit Increase Request, it asked to select region closest to you.  However in my case the nearest region is "Singapore", and in Project: Follow me, Part 2: Setting up your AWS instances, it states "Note: The AMI is available in the following regions: Oregon, North Virginia, Frankfurt, South America, Tokyo, Ohio, Seoul and Sydney. Also note that some regions may not cover p2.xlarge instances. If so, select another region.", "Singapore" is not one of the region, so I end up have to submit another limit request for "Tokyo" for which is AMI is available, which might take another 1~2 days to get it approved.

So instead of asking student to "select region nearest to you", it should be one of the region that is closest to you that have AMI available.

**Comment by kylesf** [comment]
Updated, thanks!
