### ISSUE TITLE
7.1.10 "Classes and Objects"

### ISSUE THREAD

**Issue by thatting** [udacity/robotics-nanodegree-issues#179]
I'm a bit confused?   In the embedded video (1:00 -> 1:10), the presenter says let's create a "public attribute" for class Robot, but Speed() is a public method (or behaviour) rather than an attribute?

**Comment by karimchamaa** [comment]
I usually see the attribute as an action (move, cross...). I guess this example is confusing because I should've initialized speed as a variable and not a function to really represent an attribute. Sorry about that!
