### ISSUE TITLE
ESC key stops working on RoverSim

### ISSUE THREAD

**Issue by Chambana** [udacity/robotics-nanodegree-issues#18]
on Ubuntu 16.04, the RoverSim ESC key quickly stops working as intended.  You can no longer hit ESC to give control of your cursor back to the OS, effectively locking you into the sim.  I have to Alt-Tab out of the Sim and kill the Application to close it.

**Comment by ryan-keenan** [comment]
Thank you for reporting!  should be fixed now: https://s3-us-west-1.amazonaws.com/udacity-robotics/Rover+Unity+Sims/Linux_Roversim.zip
