### ISSUE TITLE
Instructions for SVM Image Classification exercise need cleanup

### ISSUE THREAD

**Issue by jazzdman** [udacity/robotics-nanodegree-issues#180]
Perception Lesson 5, section 12 SVM image classification.  Before the exercise code, this section states:

Play with the parameter values spatial and histbin in the exercise below to see how the classifier accuracy and training time vary with the feature vector input.

There doesn't appear to be a variable named spatial in the code.

**Comment by kylesf** [comment]
Fixed, thanks.
