### ISSUE TITLE
Clarify Output of model_training.ipynb for Follow Me Project

### ISSUE THREAD

**Issue by teasp00n** [udacity/robotics-nanodegree-issues#182]
The description of the project refers to the output `model` as a `.h5` model.

This is a little confusing as it implies there is a single file with a .h5 extension but in reality the output is both the `config_model_weights` and `model_weights` files. Not sure where `.h5` is coming from other than that probably being the binary format of `model_weights`.

**Comment by haoyang-udacity** [comment]
Fixed!
