### ISSUE TITLE
can not install pcl for statistical filtering

### ISSUE THREAD

**Issue by uschas08** [udacity/robotics-nanodegree-issues#183]

**Comment by kylesf** [comment]
Please elaborate more on your issue.

**Comment by uschas08** [comment]
project 3D Perception, cannot perform statistical filtering, Error: TypeError: __cinit__() takes exactly 1 positional argument (0 given), tried with commands mentioned in lectures to re-install PCL but I could not install it stuck at a point, I tried with updating VMWARE and re-use ova file.

**Comment by kylesf** [comment]
Did you try to install with sudo?

**Comment by uschas08** [comment]
$ cd ~/RoboND-Perception-Exercises/python-pcl
$ python setup.py build
$ sudo python setup.py install
