### ISSUE TITLE
Deadline Surpassage

### ISSUE THREAD

**Issue by pravsels** [udacity/robotics-nanodegree-issues#185]
Even though I was locked out of the content due to not completing all projects before the required deadline, I was still able to bypass that blockage by clicking on the 'Resume Learning' button in Classroom home.
Was also able to submit after deadline due to the bug.
 Since last viewed content happened to be the section related to the final project and its submission.
![Screen Shot 2017-11-23 at 9.52.33 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a17185504c93700149e54f0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f06b7191a371f117294f5c5c5ecc3c4a4356bcbbd671f3e57862804e0ee4d36e5b20ce3410f8bc821cbb01ba29894fd7b5e9834ed2f42f67b6d5db1063474f4dcbed5727a29941c95df74ae54b56a6123663e6772431.png)
                                                       home page with resume learning 
![Screen Shot 2017-11-23 at 9.54.55 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a17185504c93700149e54f0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f06b7191a371f1172f4f5a5a5ecc3c4a4356bcbbd671f3e57862804e0ee4d36e5b20ce3410f8bc821cbb01ba29894fd7b5e9834ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df74ae54b56a6123663e6702431.png)
                                                                   lockage of content

**Comment by pravbeatle** [comment]
![Screen Shot 2017-11-23 at 9.52.33 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a17185504c93700149e54f0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f06b7191a371f117294f5c5c5ecc3c4a4356bcbbd671f3e57862804e0ee4d36e5b20ce3410f8bc821cbb01ba29894fd7b5e9834ed2f42f67b6d5db1063474f4dcbed5727a29941c95df74ae54b56a6123663e6772431.png)
![Screen Shot 2017-11-23 at 9.54.55 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a17185504c93700149e54f0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f06b7191a371f1172f4f5a5a5ecc3c4a4356bcbbd671f3e57862804e0ee4d36e5b20ce3410f8bc821cbb01ba29894fd7b5e9834ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df74ae54b56a6123663e6702431.png)

**Comment by jchernus** [comment]
Thanks! Udacity is aware of this issue, and a team is working on fixing this.
