### ISSUE TITLE
DroneSim installation instructions aren't clear

### ISSUE THREAD

**Issue by jazzdman** [udacity/robotics-nanodegree-issues#190]
For the Follow Me project a Drone Simulator is provided, the instructions for downloading the simulator say :

Download the latest binary of the Quad simulator for your OS and put it in a convenient location.

To this point in the class, most of the work has been done in the Ubuntu VM.  So, it seems safe to assume that "your OS" is the Ubuntu VM.  As the Slack thread below shows, this is not the case. 

https://udacity-robotics.slack.com/archives/C6P3Y6H36/p1510986442000062

The instructions above should be made explicit.  Reword them to mention native OS, or something similar.

**Comment by sahiljuneja** [comment]
Fixed, thanks!
