### ISSUE TITLE
No module named 'moviepy' in online rover lab

### ISSUE THREAD

**Issue by Kevin-La-Ra** [udacity/robotics-nanodegree-issues#193]

**Comment by Kevin-La-Ra** [comment]
In code section 11, "Make a video from processed image data"

# Import everything needed to edit/save/watch video clips
from moviepy.editor import VideoFileClip

results in 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-13e3c6f195dc> in <module>()
      1 # Import everything needed to edit/save/watch video clips
----> 2 from moviepy.editor import VideoFileClip
      3 from moviepy.editor import ImageSequenceClip
      4 
      5 

ModuleNotFoundError: No module named 'moviepy'

Adding "import moviepy" does not fix the issue.

**Comment by kylesf** [comment]
Fixed should be deployed. Sorry about any inconvenience!
