### ISSUE TITLE
Online: Rover Lab - No Module moviepy

### ISSUE THREAD

**Issue by lacvapps** [udacity/robotics-nanodegree-issues#196]
Attempting to run the rover lab notebook online results in this error

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-13e3c6f195dc> in <module>()
      1 # Import everything needed to edit/save/watch video clips
----> 2 from moviepy.editor import VideoFileClip
      3 from moviepy.editor import ImageSequenceClip
      4 
      5 

ModuleNotFoundError: No module named 'moviepy'

**Comment by kylesf** [comment]
Fixed should be deployed. Sorry about any inconvenience!
