### ISSUE TITLE
`an_image.list` does not contain valid filepaths

### ISSUE THREAD

**Issue by flores-jacob** [udacity/robotics-nanodegree-issues#197]

**Comment by flores-jacob** [comment]
Under Term 2 Lesson 6 part 4 - Image classification with DIGITS - improving performance, right after the text:
```
We can classify multiple files if we put them in the list. In the link below, execute the code block and a link to the file an_image.list will appear. Right click on an_image.list and save that to a file on your local computer(right click and "Save As"). Remember the directory in which it is saved.
```
where the student is asked to save a `an_image.list` to use to test the trained models, the `an_image.list` contains paths that do not map to actual files, resulting in the errors below when trying to use them to check the trained models.

```
Tensorflow support disabled.
"/notebooks/test_images/image-1-1.jpg" not found
"/notebooks/test_images/image-2-1.jpg" not found
"/notebooks/test_images/image-3-1.jpg" not found
"/notebooks/test_images/image-4-1.jpg" not found
"/notebooks/test_images/image-7-1.jpg" not found
"/notebooks/test_images/image-8-1.jpg" not found
"/notebooks/test_images/image-8-2.jpg" not found
2018-01-18 09:26:33 [ERROR] InferenceError: Unable to load any image from file ''/home/workspace/digits_jobs/20180118-092631-7b00/tmp0kXXhv.txt''
Traceback (most recent call last):
File "/opt/DIGITS/digits/tools/inference.py", line 293, in <module>
args['resize']
File "/opt/DIGITS/digits/tools/inference.py", line 151, in infer
raise InferenceError("Unable to load any image from file '%s'" % repr(input_list))
digits.inference.errors.InferenceError: "Unable to load any image from file ''/home/workspace/digits_jobs/20180118-092631-7b00/tmp0kXXhv.txt''"
```

Contents of the `an_image.list` file:

```
/notebooks/test_images/image-1-1.jpg
/notebooks/test_images/image-2-1.jpg
/notebooks/test_images/image-3-1.jpg
/notebooks/test_images/image-4-1.jpg
/notebooks/test_images/image-7-1.jpg
/notebooks/test_images/image-8-1.jpg
/notebooks/test_images/image-8-2.jpg
```

**Comment by priteshgudge** [comment]
Same issue for me too.
![Screen Shot 2018-01-19 at 6.58.15 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58ec8a18316bc2001a52f1a9/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455fa6b7191a37ef117234f5e5a5edd3c4a4356bcbbd671f3e57862804e0ee4d36e5b20ce3410f8bc821cbb01ba29894fd7b5e9834ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df74de24f53a711366ae5722431.png)

**Comment by kylesf** [comment]
Hi there, I have sent out for new build of image to include the data. For now please enter this command into a terminal on your digits workspace `curl -L https://s3-us-west-1.amazonaws.com/udacity-robotics/Content+Workspace+Use/lab_data.tar.gz |  tar zx -C /`
