### ISSUE TITLE
Udacity's Robotics Deep Learning AMI does not have the necessary libraries to support keras.utils.vis_utils.plot_model()

### ISSUE THREAD

**Issue by alikureishy** [udacity/robotics-nanodegree-issues#198]
Invoking the keras.utils.vis_utils.plot_model() API (via Jupyter Notebook) on an AWS EC2 instance launched with the Udacity Robotics Deep Learning AMI results in this error:
```
ImportError: Failed to import pydot. You must install pydot and graphviz for `pydotprint` to work.
```

After installing the following based on proposed solutions from other internet forums:
```
pip install pydot
pip install graphviz
```

...a new versioning discrepancy between the libraries is seen as follows:
```
AttributeError: module ‘pydot’ has no attribute ’find_graphviz’.
```

If the goal of this AMI is to provide all the requisite libraries needed for the Robotics Nanodegree Deep Learning project (i.e, the segmentation project 'Follow Me'), then it should also come pre-installed with all requisite libraries/packages needed to run keras.utils.vis_utils.plot_model().

Furthermore, the project rubric itself requires the plots of the keras models to be submitted in the project's writeup, and the pre-provided utilities code in the project too aims to offer this functionality (wrapped within the method definition -- plotting_tools.py::plot_keras_model()). So the absence of this support from the aforementioned AMI will likely affect *all* students working on that project, blocking them from completing their writeup in a straightforward manner. A case could presumably be made for this impact to reflect in the priority assigned to this bug.

**Comment by sahiljuneja** [comment]
Thanks for raising this. I have provided a comment in the Slack discussion around this as well.
