### ISSUE TITLE
L0304-Lab:Kalman Filers

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-nanodegree-issues#201]
When I roslaunch turtlebot, I get an error sayng /opt/ros/kinetic/share/gmapping/nodelet_plugins.xml not found. This way, when gazebo is loaded there is no /cmd_vel_mux node available.

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/d2337ea3-40a9-4717-af6d-4b6e17c28e3e/modules/e015f3a0-a7a3-44be-9bb9-91054b0e034e/lessons/72cae9de-deae-4579-93da-7e56bd5021fc/concepts/c917ff5b-38ea-47c3-9b13-8a31fcf70391

**Comment by karimchamaa** [comment]
Thanks for reporting the issue. Try to reload gazebo by following the steps in the instructor notes and do a "rostopic list" to check if "cmd_vel_mux" exists. And also feel free to ask your mentor for any help regarding this
