### ISSUE TITLE
Lesson 13 Build MCL in C++, Robot Class

### ISSUE THREAD

**Issue by douglasteeple** [udacity/robotics-nanodegree-issues#202]
double* sense() is a poor interface. Returning a pointer to a static array is just not great sw design. It is not thread safe, for example. Better to have sense() return a vector of values...

**Comment by karimchamaa** [comment]
Thanks for reporting this. Just updated it in GitHub to  "vector<double> sense()".
Check it out: https://github.com/udacity/RoboND-MCL-Lab
