### ISSUE TITLE
Lesson 11 Kalman Filters step 10, installing rqt_multiplot

### ISSUE THREAD

**Issue by douglasteeple** [udacity/robotics-nanodegree-issues#203]
When I enter "sudo apt-get install ros-kinetic-rqt-multiplot" I get the error: "E: Unable to locate package ros-kinetic-rqt-multiplot"...

**Comment by karimchamaa** [comment]
Which version of VM are you using? And did you run an update with "sudo apt-get udpate"?

**Comment by douglasteeple** [comment]
Hi Karim,

I am using native on TX2, so I suppose it is not supported. It did seem to be just a bad link though. Yes I did the “sudo apt-get update”

Thanks
Doug

**Comment by karimchamaa** [comment]
Haven't tested yet on the TX2, I will run a test and get back to you hopefully with a solution. Thanks for reporting the issue!
