### ISSUE TITLE
Lesson 10: Kalman Filter 15. Design of Multidimensional DF

### ISSUE THREAD

**Issue by chedanix** [udacity/robotics-nanodegree-issues#207]
It is not correct to refer S in the equation (S = H *P' *H_T + R) as the measurement covariance.

R should be the measurement covariance and (H *P' *H_T) should be the covariance of the prediction after being mapped to the sensor space.

**Comment by chedanix** [comment]
Therefore S is simply the sum of two different covariance matrices - one from measurement and the other from mapped prediction.

**Comment by jchernus** [comment]
Great catch! Fixed.
