### ISSUE TITLE
Lesson 3 - Part 3 - Simple Mover The Code - sin wave magnitude

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-nanodegree-issues#21]
In the full code listing in the 'while not rospy.is_shutdown():' the values published just come directly from the sine wave, so should be between [-1, 1]. But in the code breakdown the sine wave is multiplied by (math.pi / 2) so the output will change by [-pi/2, +pi/2]. I think this muliplication is needed to produce good output angles.

Please confirm and update the full code listing?

**Comment by kylesf** [comment]
Thanks for catching that error. I have updated the code in the classroom to the correct version!
