### ISSUE TITLE
Lesson13: Build MCL in C++   9. Resampling Wheel

### ISSUE THREAD

**Issue by chedanix** [udacity/robotics-nanodegree-issues#210]
Note that my mentor Qiang and people on Slack agree that this is an issue.

Quiz Solution Line 283 p[i] = p3[i]
The above line of code should be removed from the for-loop. If not, p would be modified in every loop and the sampling would be incorrect.
After the for-loop, assign p3 to p. You may use memcpy(p,p3,sizeof(p)) for the assignment.

**Comment by karimchamaa** [comment]
I thought of memcpy but I can't use it here since I'll need to print the values of p!

**Comment by chedanix** [comment]
I see. Thanks for fixing the bug
