### ISSUE TITLE
Inverse Sensor Model Slide

### ISSUE THREAD

**Issue by streklin** [udacity/robotics-nanodegree-issues#215]

**Comment by karimchamaa** [comment]
Hey, can you provide more details about the issue?

**Comment by streklin** [comment]
This is a bit of a nitpick, but the letter spacing on the Inverse Sensor model slide should be adjusted.  As it is the slide is very difficult to read correctly as it seems to read "ifr" instead of "if r" (see image).  While this in no way degrades ones ability  to complete the course, it is confusing when reading over the slide until whats really meant "clicks" in.
![SPACING.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a8f03e03f966d00127ef45d/125516c66e82c728ace21e0d46dba4bb00abad8ecda5fd53b652fa912a5265296b51fa7923d1e770e6137f555f5c4aac41515d44aefadc22a4a42062c80d55b98e30063e937f03a6aa8317b500bf21824c87b4be8249c8e93537aa.PNG)

If someone can find a way to simply increase that spacing a bit it would vastly improve the readibility of the slide.  Again, this really is a bit of a nitpick on my part, but its a simple fix that may reduce confusion for others.

**Comment by karimchamaa** [comment]
I agree, thanks for reporting this issue. We are currently fixing that and should replace this video soon with the newer version.
