### ISSUE TITLE
Where am I Project BUG - random obstacles near robot

### ISSUE THREAD

**Issue by chedanix** [udacity/robotics-nanodegree-issues#218]
The height of the laser rangefinder is slightly too low, resulting in random detection of the wheels once in a while. This will cause the robot to move around the non-existent obstacle.

Note that this issue has been discussed in Slack.

**Comment by sahiljuneja** [comment]
Thanks! Haven't yet noticed this in some of the runs I tried. But for now have provided students with suggestion on what to do if the above crops up.
