### ISSUE TITLE
Missing dependency in VM: vim

### ISSUE THREAD

**Issue by vaer-k** [udacity/robotics-nanodegree-issues#22]
Without vim preinstalled in the provided virtual machine image, commands like `rosed` won't work out of the box. vim should either come preinstalled or students should be directed to install it manually.

**Comment by kylesf** [comment]
Yup, great point. I think we may just switch `rosed` from its default of vim to nano. Which should settle this issue and keep people with an easier terminal interface. Will update when the change is made.

**Comment by kylesf** [comment]
This has been taken care of and you can find the updated VM in the classroom! Thanks for the help!
