### ISSUE TITLE
Typo and Improvement - Lesson 16 (11. Inverse Sensor Model)

### ISSUE THREAD

**Issue by chedanix** [udacity/robotics-nanodegree-issues#224]
Alpha shown in the picture and video is not correct. After reading Probabilistic Robotics by Thrun, I believe alpha is the range within which the cells will be marked as occupied. Therefore the value of alpha should be about the size of a cell.

Also, please add somewhere in the lecture that  a sonar rangefinder is used for the Inverse Sensor Model. It confused me for a long time because I thought a laser rangefinder was used and wondered where the "measurement cone" came from.

**Comment by karimchamaa** [comment]
Thanks for reporting the issues and sorry for the confusion. It's all being fixed in the classroom, please take a look.

**Comment by chedanix** [comment]
I just took a look. It hasn't been fixed yet, right?

**Comment by karimchamaa** [comment]
The picture/video hasn't been fixed, just added the description - summary and mentioned that it's a sonar rangefinder sensor
