### ISSUE TITLE
Some lessons still suggest to contact Live Help

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-nanodegree-issues#227]
E.g:
https://classroom.udacity.com/nanodegrees/nd209-beta/parts/f491093d-8e67-4eab-8102-87bae095ca79/modules/0573f9ff-2e23-48cd-87d0-af24d758348a/lessons/ef841d31-8c53-49b3-8da3-a9d1523adef0/concepts/e4a704e8-9490-4aff-b478-85e3f29fd4b5

**Comment by haoyang-udacity** [comment]
Need to go through all quizzes. This one fixed though.
