### ISSUE TITLE
ROS env variables are pre-sourced

### ISSUE THREAD

**Issue by vaer-k** [udacity/robotics-nanodegree-issues#23]
In section 2 lesson 1, "intro to ros", we are directed to source the bash script that loads environment variables, but the source command has at this point already been executed by default in the provided .bashrc, so the tutorials do not align with the actual experience of using the virtual machine.

**Comment by adammalpass** [comment]
I reported this already - please see issue 15.

**Comment by kylesf** [comment]
Thanks for reporting. We are currently working on this. For any updates please check [here](https://github.com/udacity/robotics-nanodegree-issues/issues/15)
