### ISSUE TITLE
Lesson 22: Q-Learning Lab

### ISSUE THREAD

**Issue by thatting** [udacity/robotics-nanodegree-issues#230]
In lesson 22 (Q-Learning Lab) section 5 (Q-Learning Notebook):

There is a missing/undisplayed diagram about halfway down the Q-Learning Notebook.

It should appear after following text:

"4. Traditional RL = Q-learning

Q-learning is one of the most popular approaches in reinforcement learning, to determine which action is optimal on each state.

At each time step tt, after taking an action atat and given reward rt+1rt+1 and next state st+1st+1, the old Q-value Q(st,at)Q(st,at) is updated by the following rule" 
.
.
I'm not sure if it has anything to do with my browser, but I've tried both in Firefox and Chrome and get the same result.

**Comment by danainschool** [comment]
Thank you - the equation was missing but has been restored.
