### ISSUE TITLE
Lesson 23: Introduction to Controls - 22. Putting It All Together

### ISSUE THREAD

**Issue by lwohlhart** [udacity/robotics-nanodegree-issues#232]
If I'm not mistaken the provided solution.py incorrectly implements the smoothing of the error derivative 

```
#@line106
d = self.kd_ * (self.alpha * delta_error / delta_time + (1 - self.alpha)  * self.last_error_)
```
this implementation alpha-interpolates between the current error-derivative and the previous error value (instead of the previous error derivative)

we would need something like:
```
d = self.kd_ * delta_error / delta_time
if len(self.u_d) > 0:
    d = self.alpha*d + (1.0 - self.alpha)*self.u_d[-1]
```

**Comment by haoyang-udacity** [comment]
Updated, thank you.
