### ISSUE TITLE
Please make Jupyter notebook data and assets for RL labs available for home use

### ISSUE THREAD

**Issue by cpowell** [udacity/robotics-nanodegree-issues#233]
These work great in the online workspace, but it'd be nice to have them for outside the lab.

**Comment by danainschool** [comment]
Thank you for your comment.  The notebooks and images can be downloaded directly from the workspace for use in another environment. To get to the file list, choose <File><Open...> from the notebook.  Select any file to see the command selections.  If it is a running notebook, first click <Shutdown>, then a new set of commands will appear in the menu for the selected file including <Download>.  Files can only be downloaded one at a time, so for the "image" files, double-click on the directory to see them individually.   A repo for these is expected to be made public at a later time.
