### ISSUE TITLE
Term 1, 6.2.2: Active Sensors Typo

### ISSUE THREAD

**Issue by delvingdeep** [udacity/robotics-nanodegree-issues#234]
There seems to be minor typo in Concept 6: Perception, Module 2: Introduction to 3D Perception and Lesson 2: `Active sensor`.

The first table is about difference between Active and Passive sensors; but the Table heading are does not match. 

The Heading should be `Passive Sensors` instead of `Passive Sensing` or the either way `Active 
Sensing` and not `Active Sensors`.

**Comment by delvingdeep** [comment]
![Screen Shot 2018-03-29 at 6.11.56 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59152178d5571c0020cf1e52/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456fa6b7191a37ef1132a4f5a595ecc3c4a4356bcbbd671f3e57862804e0ee4d36e5b20ce3410f8bc821cbb01ba29894fd7b5e9834ed2f42f67b6d5db1063474f4dcbed5727a19141c95df449e24b54a2143263e0712431.png)

**Comment by sahiljuneja** [comment]
Fixed. Thanks!
