### ISSUE TITLE
Map my world Troubleshooting update

### ISSUE THREAD

**Issue by Olcina** [udacity/robotics-nanodegree-issues#241]
In the project 3 of the second term point 12. Would be very nice to add the following link as one of the possible solution to the problem "RGB-D point cloud appears to be pointing up" the other solutions are far way more complicated and this worked for my when setting up the project in the JetsonTX2.

https://answers.ros.org/question/232534/gazebo-camera-frame-is-inconsistent-with-rviz-opencv-convention/

**Comment by haoyang-udacity** [comment]
Added! Thank you for the suggestion!
