### ISSUE TITLE
Term 2, Robotics Software Engineer Nanodegree Program, Lesson 27: Lab: Path Planning

### ISSUE THREAD

**Issue by douglasteeple** [udacity/robotics-nanodegree-issues#244]
The output window in this whole lesson on MacOSX Sierra, Safari, shows a very narrow and unreadable x size. I have a screen shot but don't know how to attach it...

**Comment by douglasteeple** [comment]
![Screen Shot 2018-04-28 at 2.44.02 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a74954151908b00113c758c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456fb6b7191a37af1162f4f5f5d5ecc3c4a4356bcbbd671f3e57862804e0ee4d36e5b20ce3410f8bc821cbb01ba29894fd7b5e9834ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df44fe84b56a4123060e7762431.png)

**Comment by karimchamaa** [comment]
![Screen Shot 2018-04-30 at 1.50.01 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59efda092b78160011a98ec6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276457f36b7191a379f1172b4f5f5e5ecc3c4a4356bcbbd671f3e57862804e0ee4d36e5b20ce3410f8bc821cbb01ba29894fd7b5e9834ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ee04f54a0103760e6762431.png)

**Comment by karimchamaa** [comment]
I just tried it on a MacOSX Sierra Safari browser and it's working fine! Maybe deleting cache and cookies will solve your problem.
