### ISSUE TITLE
Heuristic for A*

### ISSUE THREAD

**Issue by haoyang-udacity** [udacity/robotics-nanodegree-issues#248]
About the quiz in Lesson29 Topic 8 A* Real World Map, why is the heuristic grid generated without using the goal location? Shouldn't the heuristic values radiate out from the goal location?
https://udacity-robotics.slack.com/archives/C4G6J1REJ/p1528304759000545

**Comment by karimchamaa** [comment]
Updated and introduced Manhattan, Euclidean, and chebyshev distances
