### ISSUE TITLE
A typo in lesson #11 equation #5

### ISSUE THREAD

**Issue by JafarAbdi** [udacity/robotics-nanodegree-issues#256]
Shouldn't the equality sign in the equation #5 be matrix multiplication 

https://classroom.udacity.com/nanodegrees/nd209/parts/c199593e-1e9a-4830-8e29-2c86f70f489e/modules/8855de3f-2897-46c3-a805-628b5ecf045b/lessons/87c52cd9-09ba-4414-bc30-24ae18277d24/concepts/613a7740-3575-4384-a2b2-c9f0b18924b4

**Comment by JafarAbdi** [comment]
By the hashtag sign, I mean number :D

**Comment by karimchamaa** [comment]
Fixed in equation 5 and the quiz! Thanks for reporting.
