### ISSUE TITLE
Lesson 12 section 3 Typo in QUESTION 2 OF 2

### ISSUE THREAD

**Issue by JafarAbdi** [udacity/robotics-nanodegree-issues#267]
The one in the second row and third column should be there https://imgur.com/a/RsOYW4z

**Comment by xCASx** [comment]
Spent more than a week at Khan Academy to refresh my knowledge on linear algebra to find out what's wrong with my calculations. All this just to finally figure out that it's just a typo in the assignment.

**Comment by thecarlos** [comment]
Had the same issue, did the derivation of the inverse by hand and thought the scoring was wrong.  Didn't think that it could have been a typo.
