### ISSUE TITLE
Lesson 3- Part 3 missing explanation for  rospy.init_node

### ISSUE THREAD

**Issue by GilMe** [udacity/robotics-nanodegree-issues#27]
In the code that is pasted in the top, rospy is initialized with: 'rospy.init_node('arm_mover', anonymous=True)'
In the line-by-line explanation of the code its: 'rospy.init_node('arm_mover')'
There is no explanation to what 'anonymous=True' does.

**Comment by ryan-keenan** [comment]
Great catch!  This has been fixed now: `The argument anonymous=True makes sure that you always have a unique name for your node`
