### ISSUE TITLE
Is picking_up flag does not reset in simulator

### ISSUE THREAD

**Issue by Dulluhan** [udacity/robotics-nanodegree-issues#28]
After pick_up flag is sent through socket, picking_up flag is asserted on Unity end. The result of this is that the rover no longer takes any commands manual or autonom4 a sample nearby. Could be just a problem with my build. Ubuntu 16.04, Roversim.x86_64

**Comment by Dulluhan** [comment]
After pick_up flag is sent through socket, picking_up flag is asserted on Unity end. The result of this is that the rover no longer takes any commands manual or autonoms, with or without a sample nearby. Could be just a problem with my build. Ubuntu 16.04, Roversim.x86_64

**Comment by kylesf** [comment]
Is this with the most up to date simulator?

**Comment by kylesf** [comment]
Any updates to this?

**Comment by ryan-keenan** [comment]
I'll close this issue for now as this should be fixed in the most recent updates to the project repo.  Please reopen if problems persist!
