### ISSUE TITLE
Update OpenGL 3.3

### ISSUE THREAD

**Issue by gwwang16** [udacity/robotics-nanodegree-issues#29]
OpenSchool cannot work with the default opengl version 2.1 in VM.  I updated it succesfully in local following this link. https://www.mesa3d.org/vmware-guest.html

**Comment by kylesf** [comment]
Has any upgrades to OpenGL caused any issues with your pick and place project?

**Comment by gwwang16** [comment]
@kylesf No, it has no effect on pick place project. As I mentioned before, Openschool cannot work with the default opengl version 2.1 in VM, which is introduced in Udacity Explorer -- Biologically inspired robots.

**Comment by kylesf** [comment]
Will not be upgrading VM to OpenGL 3.3 due to possible student hardware issues.
