### ISSUE TITLE
Environment setup clarification

### ISSUE THREAD

**Issue by Chambana** [udacity/robotics-nanodegree-issues#3]
In the first module, there is a section on setting up your environment.  A link in the module refers you to a Udacity guide that instructs you to install anaconda.  Then it refers you to a link that wants you to install miniconda as part of the RoboND env setup (but you just installed Anaconda).  It works just fine, but it could be clearer.

**Comment by ryan-keenan** [comment]
Thanks for reporting!  I just added a parenthetical statement to this effect in the lesson
