### ISSUE TITLE
keyboard setting

### ISSUE THREAD

**Issue by natamorales** [udacity/robotics-nanodegree-issues#30]
Not really an issue ... while one remembers where the characters are =)  but although I selected spanish keyboard, in VM v2 it remains in english ...

**Comment by kylesf** [comment]
Thanks for sharing. I will look into it and figure out a fix. Ill get you the steps needed to fix as well!

**Comment by kylesf** [comment]
Were you able to find a solution to change the key mapping? From what I have looked up the keyboard should be switched to Spanish. I do not have a keyboard to test though!

**Comment by kylesf** [comment]
Updated VM will be in classroom by EOD
