### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mi7flat5** [udacity/robotics-nanodegree-issues#36]
in section 14 of the kinematics project 'Inverse Kinematics with Kuka KR210', in this sentence 'Now that you have the wrist center position, follow the simple math presented in this section to derive the equations for first three joints.' The link on this sends me to  a beta version of the ND and I get a error saying I don't have access.

**Comment by sahiljuneja** [comment]
Hey, could you refresh the page and share that URL here? Because it should not point to the beta version.

**Comment by sahiljuneja** [comment]
Okay, found the problem. Fixing it. Thanks!

**Comment by sahiljuneja** [comment]
Okay, should be fine now.

**Comment by adammalpass** [comment]
I still have this issue with many links in the Kinematics section
