### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by mi7flat5** [udacity/robotics-nanodegree-issues#37]
Both links in the project rubric for the pick and place project link to beta ND and are not accessible

**Comment by mi7flat5** [comment]
The rubric also mentions a writeup template that I don't see in the repository.

**Comment by adammalpass** [comment]
I found same issue. The rubric also mentions there is an example diagram inside the writeup template that I'd really like to reference!

**Comment by ryan-keenan** [comment]
Thanks for reporting and sorry for the delay.  The links in the rubric are fixed and the repo is updated now with a writeup_template.md.  Nothing fancy there just an example doc to get started with the writeup.
