### ISSUE TITLE
Jupyter still needs plt.show()

### ISSUE THREAD

**Issue by Dulluhan** [udacity/robotics-nanodegree-issues#4]
There is a code block in Lesson 1 Project.6.Persepective Transform that has comment saying plt.show() should not be needed in Jupyter, however, in my case it seems that it doesn't show unless I have that. It is the same case if I was to copy the previous section's code to try out on my own computer. It would be helpful to let people know that to view the plt object locally, .show() is needed.

**Comment by Dulluhan** [comment]
https://puu.sh/w0rjP/a5878a6496.png

**Comment by ryan-keenan** [comment]
Thanks for reporting this!  As far as I know plt.show() has no adverse effects even if it's not needed (not sure why some notebooks seem to need it others don't) so I've gone through and deleted the comments saying `# not needed in Jupyter notebook`
