### ISSUE TITLE
incorrect info in code comments

### ISSUE THREAD

**Issue by Chambana** [udacity/robotics-nanodegree-issues#41]
I think there is incorrect info in 2 places in the exercise labeled, "Homogeneous Transforms and their Inverse".  In the solution code, the comment above P's initialization says "# Construct P in {A}".  However, P at this point is in B frame not A.  In the Starter code, the problem setup comment says "Let P be a vector expressed in frame {C} with (x,y,z)" .  P is in B frame not C frame.  C frame was the previous exercise.

**Comment by jchernus** [comment]
Thanks!
