### ISSUE TITLE
Diagram needs revision

### ISSUE THREAD

**Issue by irishMee** [udacity/robotics-nanodegree-issues#42]

**Comment by irishMee** [comment]
in the Homogeneous Transforms and their Inverse lesson and in the first diagram on the page, I believe that the vector labeling for A rAo/Bo and the vector  r P/Ao need to be switched. Image that I am talking about is shown below with my recommended switch.
![l01-14-l-homogeneous-transforms-and-their-inverse-01v2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59457d2f0b68f60020fb905c/125516c66e82c728ace21e0d46e4c4cb6ed3d7e483a4b74ca952f791274328663a49b739718bf02eb0507612420e10f85c1c0711a5bb9472f8f06932c90916edd02b5d66da2f51eee7d84aec45a82a994a8cb4bf8e18c8e13c71e38b8c4b3e1e0c1a89ad5e60a99b59d44ab41abf190af94a7c36a4643c6e4496147428626021a9fad955868061aca85d.png)

**Comment by ryan-keenan** [comment]
Thanks for reporting!  This looks like [issue #38]( https://waffle.io/udacity/robotics-nanodegree-issues/cards/594446fbe8304a00263d6354) so will assign to @jchernus as well and move to "in progress".
