### ISSUE TITLE
Cannot scroll livehelp window downwards

### ISSUE THREAD

**Issue by flores-jacob** [udacity/robotics-nanodegree-issues#48]
After posting query to livehelp, livehelp window pops up, showing the connection was successful. However, there is no way to scroll the window downards to see if the live expert is able to respond to the query.  There is no input field to type any responses either.

After clicking the "End Chat" button, the live help window is now scrollable, revealing that the live expert was available all along and was waiting for a response.

Browser: Firefox 54.0 (64-bit) on Ubuntu 16.04

**Comment by frozenamazon** [comment]
+1.
Chrome should fix the issue, but it is utterly broken on Firefox

**Comment by kylesf** [comment]
Fixed with updates. Thanks!
