### ISSUE TITLE
Feedback: more interactive livehelp

### ISSUE THREAD

**Issue by frozenamazon** [udacity/robotics-nanodegree-issues#53]
There are times where livehelp takes more than 10 minutes (I waited for nearly 30 minutes) for a reply. I understand that there may be a queue, but from a UX perspective, any chance of showing the queue number, instead of just the waiting indicator. I am not sure whether the livehelp is just broken or there is a massive queue.

**Comment by kylesf** [comment]
We have moved this into internal tickets and assure you its being addressed! Thanks for your input!
