### ISSUE TITLE
Feedback: hope improve course content quality

### ISSUE THREAD

**Issue by gwwang16** [udacity/robotics-nanodegree-issues#58]
There are so many typos, mistakes, inconsistent conventions and vague things in part.2 course content, it looks it is still in half-baked. I cannot believe that you can release them as formal content without proof reading, didn't add contents anymore and didn't provide any extra learning source links. We came here with expensive paid fee to learn not to be laboratory rats.

**Comment by kylesf** [comment]
Thanks for your concerns. We are actively trying to maintain the highest quality. I will pass your feedback along!
