### ISSUE TITLE
Feedback: hope conduct more interactions with students

### ISSUE THREAD

**Issue by gwwang16** [udacity/robotics-nanodegree-issues#59]
There is few interaction and feedback about course problems. You don't want to have a forum, so the slack is our main discussing place, right? But there is no official people come out to answer questions or clarify uncorrect understandings among so many posted problems in slack channel.  You have adviced us to use LiveChat, but the dialogue quality in LiveChat is too worrisome, All of them (>10) have negative effects on my understanding.

**Comment by kylesf** [comment]
LiveHelp and its mentors are being improved daily. A course wiki is being established and many other things are being put in place (such as office hours) to close this gap. Thanks for your thoughts!
