### ISSUE TITLE
Feedback: about mentors in LiveChat

### ISSUE THREAD

**Issue by gwwang16** [udacity/robotics-nanodegree-issues#60]
I don't understand why you insist on using this terrible product 'LiveChat' to answer our questions, about salary calculation? It's the best way to do it in a forum or even in slack channel. Because livechat is a closed space, we cannot evalute the dialogue quality, don't know whether they are right at that time, and cannot reuse QA content. 
The chat window is too small and has no notify sounds when the chat is connected and recieve message. It always cost 5-20 min to connect LiveChat, we have to stare at this window all the time! many monsters replied very slow, we have to stare at the window all the time! The file upload window is not support drag and drop.
Hope you'll achieve more progress on LiveChat using experience and dialogue quality.

**Comment by kylesf** [comment]
We have moved this into internal tickets and assure you its being addressed! Thanks for your input!
