### ISSUE TITLE
Gap in understanding inverse kinematics using geometry

### ISSUE THREAD

**Issue by paramrajpura** [udacity/robotics-nanodegree-issues#63]
Understanding the geometric IK not only requires basic geometry knowledge, but some visualization skills.
The example provided for IK in lesson definitely helps but doesn't cover enough diagrams/visualizations.
Referring Spong's textbook and help from Slack community finally made things clear.
For a fix, I request adding few additional materials to refer for this particular concept and P2 overview.

**Comment by kylesf** [comment]
Added some new modules and a video walkthrough! Thanks for the feedback!
