### ISSUE TITLE
Live Help Credibility

### ISSUE THREAD

**Issue by paramrajpura** [udacity/robotics-nanodegree-issues#64]
Live help has been a well intended but poorly implemented solution.
The solutions from Live experts have been hardly helpful even after the slow paced responses.
Requesting to either train mentors well enough or at-least a thorough check on their version of  project implementations before releasing materials to students shall be helpful.

Technical Issues:
1. Limited browser support
2. Inconsistent chat sessions(Connectivity Issues)
3. Inconsistent File upload functionality

**Comment by kylesf** [comment]
We have moved this into internal tickets and assure you its being addressed! Thanks for your input!
