### ISSUE TITLE
More guidance on the projects

### ISSUE THREAD

**Issue by frozenamazon** [udacity/robotics-nanodegree-issues#65]
It feels like a lot of knowledge has tried to be passed on without much explanation. Yes it is good for the students to self learn, but it is literally throwing into the dark. In the event the material is not updated, more guidance is required. ie mentors that can actually explain and understand the problems faced

**Comment by sahiljuneja** [comment]
Is this specific to any project? 

Any particular pain points you faced for any project in regards to this so that we can try focus on that?

**Comment by kylesf** [comment]
Updates to this @frozenamazon ?

**Comment by lisajlau** [comment]
I was referring to the kinematics project. But I see improvement on the perception project. Sorry didn't see the notifications , everything went to spam.

**Comment by kylesf** [comment]
Well Kinematics has been updated and additional content added!
