### ISSUE TITLE
Waffle board doesnt work properly on mobile

### ISSUE THREAD

**Issue by frozenamazon** [udacity/robotics-nanodegree-issues#66]
It doesnt scroll when viewed on a mobile screen

**Comment by sahiljuneja** [comment]
Hey, yeah it's not the best optimized website for the phone. 

But you can scroll on phone, you just have to scroll close to individual scrollbars which is annoying and confusing. So you can't scroll a particular section (like "Backlog") if you try to scroll by moving your finger in the center of the area. You will have to scroll by sliding your finger close to the scrollbar (invisible by default) on the right side of that subsection. I know this is perhaps more confusing, but that's the only way I know.

I am not sure how to provide feedback back to waffle. If I do I will link here, but I recommend trying to find a way to send them feedback directly! :)
