### ISSUE TITLE
Project review

### ISSUE THREAD

**Issue by lisajlau** [udacity/robotics-nanodegree-issues#68]
The review took three days, as opposed to 24 hours. I understand that it was a holiday but it would be good to notify the students that there might be a delay. I am sure they understand instead of letting them guess.

**Comment by ryan-keenan** [comment]
Thanks for the feeback!  We try to stay on top of any potential blockers for reviews and let students know when we run into the, but sometimes things slip.  You can be assured that we'll be making every effort to keep things fast and efficient going forward!
