### ISSUE TITLE
Rotation matrix explanation code is wrong

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-nanodegree-issues#7]
In section Map to World Coordinates in the Project: Search and Sample Return part there is an error in the rotation matrix code. The image showing how the rotation matrix should be and the formulas are correct. However beneath that the code implemenation is wrong.

It says y_rotated = xpix * np.sin(yaw_rad) + ypix * np.sin(yaw_rad), but it should be:

y_rotated = xpix * np.sin(yaw_rad) + ypix * np.cos(yaw_rad).

The final part should be cos, not sin.

**Comment by ryan-keenan** [comment]
Great catch!  fixed now
