### ISSUE TITLE
Already completed projects now showing as "past due"

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-nanodegree-issues#71]
All of a sudden all the projects I had already completed (Rover, Pick & Place, Github) are showing as uncompleted and "past due". Looks like a bug - please can you check?

**Comment by sahiljuneja** [comment]
That sometimes pops up. Usually waiting for a bit and refreshing a few times fixes things. But regardless, don't worry, even if that shows up you won't have to resubmit anything. It's all still there!

Just noticed Chris mentioned the same in the Slack, and it's working for you now. Good to know :)
