### ISSUE TITLE
Inconsistent notation for rotation

### ISSUE THREAD

**Issue by lisajlau** [udacity/robotics-nanodegree-issues#73]
In kinematics -> forward kinematics, lectures 7 video and lecture 8, there is an inconsistency in notation for rotation. 
Lecture 7 states for an extrinsic rotation
Rzyx = Rx*Ry*Rz

In lecture 8, along a rotation in x-y-z, 
Rzyx = Rz*Ry*Rx

Would have shared a snapshot but can't seem to be able to attach anything

**Comment by lisajlau** [comment]
[Uploading Pasted image at 2017_07_06 03_44 PM.png...]

**Comment by lisajlau** [comment]
[Uploading Screenshot_20170706-083221~2.png...]

**Comment by kylesf** [comment]
@sahiljuneja Did we make a JIRA ticket for this?

**Comment by sahiljuneja** [comment]
No need. I just fixed it. Will close this now.
