### ISSUE TITLE
typo in Lesson 2 "Forward and Inverse Kinematics"

### ISSUE THREAD

**Issue by chedanix** [udacity/robotics-nanodegree-issues#78]
--Go to 13. DH Parameter Assignment Algorithm.
--Look at step 6. The endpoints of .......
--There is a typo in "For i from 1 to n", it should be "from 1 to n-1" because n refers to the end effector.

**Comment by kylesf** [comment]
I am not sure what you mean. Can you elaborate?

**Comment by chedanix** [comment]
![capture](https://user-images.githubusercontent.com/17792941/28702304-c10ee7e8-7321-11e7-9a22-c7bebe64e139.PNG)

The initial frame and the end-effector frame should be treated differently, but the "n" in the picture refers to the end-effector frame. Let me know what you think. I could be wrong.

**Comment by kylesf** [comment]
Okay, great. Made that fix. Thanks!
