### ISSUE TITLE
Calibration, Filtering and Segmentation, Lesson 8

### ISSUE THREAD

**Issue by sychaichangkun** [udacity/robotics-nanodegree-issues#83]
In Lesson 8 Point Cloud Filtering, there should be 5 filters to be explored. They are:

VoxelGrid Downsampling Filter
PassThrough Filter
RANSAC Plane Fitting
ExtractIndices Filter
Outlier Removal Filter(Statistical Outlier filter)

**Comment by kylesf** [comment]
Thanks, updated!
