### ISSUE TITLE
Incorrect project reference in training_helper.py

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-nanodegree-issues#84]
In the perception Exercise 3 there is a training_helper.py file with some helper functions.

FYI in the copyright at the top it says it is for the Robotic Arm Pick & Place project, but it is not. It is for the Perception exercises.

https://github.com/udacity/RoboND-Perception-Exercises/blob/master/Exercise-3/sensor_stick/src/sensor_stick/training_helper.py

**Comment by kylesf** [comment]
Fixed, thanks!
