### ISSUE TITLE
Lesson 5.8 - Surface Normals, Graphic Improvements

### ISSUE THREAD

**Issue by dandrews7396** [udacity/robotics-nanodegree-issues#87]
The Graphic that is shown at 1:12 could be made more clear.

The arrows showing the normal to each side of the shapes would be improved by pointing in their correct plane, and from each visible side.

for example:

- The sphere should be covered in normals (within reason)

- The Cuboid and Pyramid should have a normal originating from the centre of each visible side.

Currently the Sphere shows a normal at random intervals over it's surface, The Cuboid shows a normal extending from just two of it's edges and not in the correct plane, and the Pyramid shows the normal to it's reverse side as originating from it's visible side.

**Comment by sahiljuneja** [comment]
To my knowledge, this is being worked upon for improvement. Hopefully, will have an update on it soon in the classroom.
