### ISSUE TITLE
I have checked off the box that says "dont show me this again" but it still shows up

### ISSUE THREAD

**Issue by Youssef-Khaky** [udacity/robotics-nanodegree-issues#94]
When I log into the nano-degree, the live help section pops up and tells me that I can use it if I am stuck, but it keeps coming back again even though I said not to show it again.

**Comment by sahiljuneja** [comment]
Hey, could you please email mentorship-support@udacity.com about this? The right team can then look into it directly and follow-up with you if needed for anything. Thanks!
