### ISSUE TITLE
Poorly structured reference to lesson material

### ISSUE THREAD

**Issue by vaer-k** [udacity/robotics-nanodegree-issues#98]
In lesson 5 section 17 the following statement is made: "First you have to build out your node for segmenting your point cloud. This is where you'll bring in your code from Exercises 1 and 2." It's not clear what this text refers to. I think the reference to "exercises 1 and 2" should be more specific or even link directly to the content. Reading this after a brief hiatus from studies, I have no idea where in the lessons to look for these examples, and it's also difficult to infer the reference based on the content described.

**Comment by sahiljuneja** [comment]
I have added links to the beginning sections for each Exercise to make it easier to go through and revise those sections. Thanks!
